### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by GianniBYoung** [AlexSciFier/neonlink#54]
Error when Running `docker compose up`

```docker compose up
[+] Running 2/2
 ✔ Network neonlink_default  Created                                                                                            0.1s
 ✔ Container neonlink        Created                                                                                            0.2s
Attaching to neonlink
neonlink  |
neonlink  | /app/node_modules/better-sqlite3/lib/database.js:63
neonlink  | 		[util.cppdb]: { value: new addon.Database(filename, filenameGiven, anonymous, readonly, fileMustExist, timeout, verbose || null, buffer || null) },
neonlink  | 		                      ^
neonlink  |
neonlink  | SqliteError: unable to open database file
neonlink  |     at new Database (/app/node_modules/better-sqlite3/lib/database.js:63:26)
neonlink  |     at Object.<anonymous> (/app/db/connect.js:2:10)
neonlink  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
neonlink  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
neonlink  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
neonlink  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
neonlink  |     at Module.require (node:internal/modules/cjs/loader:1100:19)
neonlink  |     at require (node:internal/modules/cjs/helpers:108:18)
neonlink  |     at Object.<anonymous> (/app/app.js:5:18)
neonlink  |     at Module._compile (node:internal/modules/cjs/loader:1198:14) {
neonlink  |   code: 'SQLITE_CANTOPEN'
neonlink  | }
neonlink exited with code 0
```

**Docker Compose (Docker version 24.0.4, build 3713ee1):**

```version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    volumes:
      - ./bookmarks.sqlite:/app/db/bookmarks.sqlite
      - ./background:/app/public/static/media/background
    restart: always
    ports:
      - "80:3333"```

**Comment by GianniBYoung** [comment]
As per [this release](https://github.com/AlexSciFier/neonlink/releases/tag/v1.3.0)

I just needed to create the bookmarks.sqlite file and mount the folder it is contained in. Updated Docker file:

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      -./data:/app/data
      - ./background:/app/public/static/media/background
    restart: unless-stopped
    ports:
      - "3338:3333"
