### ISSUE TITLE
SqliteError: unable to open database file

### ISSUE THREAD

**Issue by bannert1337** [AlexSciFier/neonlink#56]
When trying to create a Docker container with the command 

`docker run -p {80}:3333 -v {/path/to/data}:/app/data -v {/path/to/backgrounds}:/app/public/static/media/background alexscifier/neonlink:latest` 

given on the GitHub page, the created container stops directly after the start and this error is shown in the log:

`/app/node_modules/better-sqlite3/lib/database.js:63
		[util.cppdb]: { value: new addon.Database(filename, filenameGiven, anonymous, readonly, fileMustExist, timeout, verbose || null, buffer || null) },
		                       ^
SqliteError: unable to open database file
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:63:26)
    at Object.<anonymous> (/app/db/connect.js:2:10)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/app/app.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1198:14) {
  code: 'SQLITE_CANTOPEN'
}`

**Comment by bannert1337** [comment]
I created Docker volumes and replaced the path mappings accordingly.

**Comment by julichan** [comment]
Hello, is this an update or a first-time installation?
Can you share your actual day cker command line and perform a `ls -la` in the parent directory of the data directory.
