### ISSUE TITLE
Internal Server Error when input URL

### ISSUE THREAD

**Issue by xrfmkrh** [AlexSciFier/neonlink#95]
after version 1.4.12, Internal Server Error occur when add bookmark - input URL

**Comment by AlexSciFier** [comment]
Hi, can you provide log from Docker container?

**Comment by xrfmkrh** [comment]
{"level":50,"time":1702301036035,"pid":1,"hostname":"803523d17d82","reqId":"req-vd","req":{"method":"POST","url":"/api/utils/urlinfo","hostname":"192.168.1.102:1739","remoteAddress":"192.168.1.81","remotePort":3895},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'headers')","stack":"TypeError: Cannot read properties of undefined (reading 'headers')\n    at requestHeadFromUrl (file:///app/logics/bookmarks.js:29:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.<anonymous> (file:///app/routes/api/utils/index.js:30:22)"},"msg":"Cannot read properties of undefined (reading 'headers')"}

github.com connect ECONNREFUSED 127.0.0.1:80

**Comment by AlexSciFier** [comment]
Does this error appear when adding any link, or just this one specifically?

**Comment by xrfmkrh** [comment]
Any link.
But I can add bookmark after that error.

**Comment by xrfmkrh** [comment]
error message changed to 'Error Invalid URL' at 1.4.14
