### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by marklove5102** [AlexSciFier/neonlink#97]
````bash
root@eeb563c53ad9:/neonlink# npm run dev-init --registry=https://registry.npmmirror.com

> neonlink@1.1.1 dev-init
> npm install && cd ./frontend && npm install && cd ../server && npm install


up to date in 834ms

7 packages are looking for funding
  run `npm fund` for details

up to date in 2s

115 packages are looking for funding
  run `npm fund` for details

up to date in 1s

39 packages are looking for funding
  run `npm fund` for details





root@eeb563c53ad9:/neonlink# npm run dev-start

> neonlink@1.1.1 dev-start
> concurrently --kill-others "npm run dev-server" "npm run dev-client"

[1] 
[1] > neonlink@1.1.1 dev-client
[1] > cd ./frontend && npm run start
[1] 
[0] 
[0] > neonlink@1.1.1 dev-server
[0] > cd ./server && npm run dev
[0] 
[1] 
[1] > neonlink-frontend@1.4.13 start
[1] > vite
[1] 
[0] 
[0] > neonlink-backend@1.0.0 dev
[0] > fastify start -a "0.0.0.0" -w --ignore-watch="data public" --body-limit 5242880 -l info -P app.js
[0] 
[0] sh: 1: fastify: not found
[0] npm run dev-server exited with code 127
--> Sending SIGTERM to other processes..
[1] npm run dev-client exited with code SIGTERM





root@eeb563c53ad9:/neonlink# node -v
v20.11.0


root@eeb563c53ad9:/neonlink# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@eeb563c53ad9:/neonlink# 
````

**Comment by marklove5102** [comment]
docker Build error
`````
git clone https://github.com/AlexSciFier/neonlink
cd neonlink



make@make:~/1.app/chrome/neonlink$ docker build --platform linux/amd64 --tag alexscifier/neonlink:latest .
Sending build context to Docker daemon  1.538MB
Step 1/31 : FROM --platform=$BUILDPLATFORM node:lts-slim AS ui-build
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument

`````

**Comment by AlexSciFier** [comment]
Hi, there is misstake in readme. For `dev-init` error try to install fastify-cli globaly `npm install fastify-cli --global` and run `npm run dev-start` again.
For docker build you should use [BuildKit](https://docs.docker.com/build/buildkit/). Add `DOCKER_BUILDKIT=1` before build command or use [buildx](https://docs.docker.com/engine/reference/commandline/buildx_build/).
I will update readme soon.

**Comment by marklove5102** [comment]
edge html

![image](https://github.com/AlexSciFier/neonlink/assets/12666917/7c675a2b-16a6-4362-a502-fb8811255a3a)

`````
[0] [08:35:57.514] INFO (2295): request completed
[0]     reqId: "req-1p"
[0]     res: {
[0]       "statusCode": 201
[0]     }
[0]     responseTime: 23900.057339999825
[0] javascript:__doPostBack('BtnNext','') Unsupported protocol javascript:
[0] javascript:(function(){var script=document.createElement("script");script.setAttribute("src","http://www.baidu.com/olime/bdime_open.js");document.getElementsByTagName("head")[0].appendChild(script);})(); Unsupported protocol javascript:
[0] javascript:(function(){var%20w=window,l=w.location,d=w.document,s=d.createElement('script'),e=encodeURIComponent,o='object',n='AUWLBookzhCN',u='http://www.amazon.cn/wishlist/add',r='readyState',T=setTimeout,a='setAttribute',g=function(){d[r]&&d[r]!='complete'?T(g,200):!w[n]?(s[a](%27charset%27,%27UTF-8%27),s[a](%27src%27,u+%27.js?loc=%27+e(l)+%27&b=%27+n),d.body.appendChild(s),f()):f()},f=function(){!w[n]?T(f,200):w[n].showPopover()};typeof%20s!=o?l.href=u+%27?u=%27+e(l)+%27&t=%27+e(d.title):g()}()) Unsupported protocol javascript:
[0] javascript:void((function(){if(window.bdime){bdime.open();}else{var s=document.createElement("script");s.src="http://www.baidu.com/olime/bdime_open.js";document.getElementsByTagName("head")[0].appendChild(s);}document.getElementById("keyword").focus();})()) Unsupported protocol javascript:
[0] chrome://inspect/#devices Unsupported protocol chrome:
[0] chrome://net-internals/#dns Unsupported protocol chrome:
[0] chrome://flags/#run-all-flash-in-allow-mode Unsupported protocol chrome:
[0] chrome://chrome-urls/ Unsupported protocol chrome:
[0] javascript:(function(){var script=document.createElement("script");script.setAttribute("src","https://www.baidu.com/olime/bdime_open.js");document.getElementsByTagName("head")[0].appendChild(script);})(); Unsupported protocol javascript:
[0] edge://inspect/#other Unsupported protocol edge:
[0] edge://site-engagement/ Unsupported protocol edge:
[0] edge://surf/ Unsupported protocol edge:
[0] edge://favorites/ Unsupported protocol edge:
[0] javascript:navigator.clipboard.writeText(%60%24%7Bwindow.document.title%7D%20%24%7Bwindow.location.href%7D%60).catch(o%3D%3Econsole.error(o))%3B Unsupported protocol javascript:
[0] javascript:%20(function%20()%20{var%20jsCode%20=%20document.createElement(%27script%27);jsCode.setAttribute(%27src%27,%20%27https://sparkbox.github.io/mediaQueryBookmarklet/bookmarklet-js/mediaQueryBookmarklet.js%27);document.body.appendChild(jsCode);}()); Unsupported protocol javascript:
[0] javascript:(function()%7Bvar%20scriptTag%20%3D%20document.createElement('script')%3BscriptTag.setAttribute('src'%2C%20'https%3A%2F%2Frawgit.com%2Fvbachevhx%2Fcookie-bookmarklet%2Fmaster%2Fdist%2Fcookie_bookmarklet.js')%3Bdocument.body.appendChild(scriptTag)%3B%7D)() Unsupported protocol javascript:
[0] javascript:(function()%7Bvar%20scriptURL%20%3D%20%22https%3A%2F%2Fscripts.shpg.org%2FTableThis.js%22%3B%0A%0Aif%20(window.jQuery)%20%7B%20%0A%20%20%20%20loadScript()%3B%0A%20%20%20%20%0A%7D%20else%20%7B%0A%20%20%20%20var%20jq%20%3D%20document.createElement(%27script%27)%3B%0A%20%20%20%20jq.type%20%3D%20%27text%2Fjavascript%27%3B%20%0A%20%20%20%20jq.onload%20%3D%20function()%20%7B%20%0A%20%20%20%20%20%20%20%20loadScript()%3B%0A%20%20%20%20%7D%20%20%20%0A%20%20%20%20jq.src%20%3D%20%27%2F%2Fcode.jquery.com%2Fjquery-2.1.3.js%27%3B%0A%20%20%20%20document.getElementsByTagName(%27head%27)%5B0%5D.appendChild(jq)%3B%0A%7D%0A%0A%0Afunction%20loadScript()%20%7B%0A%0A%20%20%2F%2Fadd%20new%20script%20file%20to%20the%20DOM%0A%0A%20%20%20%20var%20A%20%3D%20document.createElement(%27script%27)%3B%0A%20%20%20%20A.type%20%3D%20%27text%2Fjavascript%27%3B%20%0A%20%20%20%20A.onload%20%3D%20function()%20%7B%20%0A%20%20%20%20%7D%20%20%20%0A%20%20%20%20A.src%20%3D%20scriptURL%3B%0A%20%20%20%20document.getElementsByTagName(%27head%27)%5B0%5D.appendChild(A)%3B%0A%20%20%20%20%0A%7D%0A%7D)() Unsupported protocol javascript:
[0] javascript:(function(){var s = document.createElement('script');s.type='text/javascript';s.src='https://dsheiko.github.io/pixel-perfect-bookmarklet/bookmarklet.js?v=%27+parseInt(Math.random()*99999999);document.body.appendChild(s);void(0);}()); Unsupported protocol javascript:
[0] Unsupported protocol chrome:
[0] Unsupported protocol chrome:
[0] Unsupported protocol chrome:
[0] Unsupported protocol chrome:
[0] Unsupported protocol edge:
[0] Unsupported protocol edge:
[0] Unsupported protocol edge:
[0] Unsupported protocol edge:
[0] chrome://inspect/#devices updated!
[0] chrome://net-internals/#dns updated!
[0] chrome://flags/#run-all-flash-in-allow-mode updated!
[0] chrome://chrome-urls/ updated!
[0] edge://inspect/#other updated!
[0] edge://site-engagement/ updated!
[0] edge://surf/ updated!
[0] edge://favorites/ updated!
[0] TypeError: Invalid URL
[0]     at new URL (node:internal/url:775:36)
[0]     at parseIcon (file:///neonlink/server/helpers/parsers.js:34:10)
[0]     at parseHtml (file:///neonlink/server/helpers/parsers.js:21:14)
[0]     at file:///neonlink/server/logics/bookmarks.js:74:25
[0]     at Array.forEach (<anonymous>)
[0]     at batchUpdateLinks (file:///neonlink/server/logics/bookmarks.js:72:13)
[0]     at Object.<anonymous> (file:///neonlink/server/routes/api/utils/index.js:50:12)
[0]     at preHandlerCallback (/neonlink/server/node_modules/fastify/lib/handleRequest.js:137:37)
[0]     at validationCompleted (/neonlink/server/node_modules/fastify/lib/handleRequest.js:121:5)
[0]     at preValidationCallback (/neonlink/server/node_modules/fastify/lib/handleRequest.js:98:5) {
[0]   code: 'ERR_INVALID_URL',
[0]   input: '/favicon.ico',
[0]   base: "javascript:__doPostBack('BtnNext','')"
[0] }
[0] second error, exiting
[0] TypeError: Invalid URL
[0]     at new URL (node:internal/url:775:36)
[0]     at parseIcon (file:///neonlink/server/helpers/parsers.js:34:10)
[0]     at parseHtml (file:///neonlink/server/helpers/parsers.js:21:14)
[0]     at file:///neonlink/server/logics/bookmarks.js:74:25
[0]     at Array.forEach (<anonymous>)
[0]     at batchUpdateLinks (file:///neonlink/server/logics/bookmarks.js:72:13)
[0]     at Object.<anonymous> (file:///neonlink/server/routes/api/utils/index.js:50:12)
[0]     at preHandlerCallback (/neonlink/server/node_modules/fastify/lib/handleRequest.js:137:37)
[0]     at validationCompleted (/neonlink/server/node_modules/fastify/lib/handleRequest.js:121:5)
[0]     at preValidationCallback (/neonlink/server/node_modules/fastify/lib/handleRequest.js:98:5) {
[0]   code: 'ERR_INVALID_URL',
[0]   input: '/favicon.ico',
[0]   base: 'javascript:(function(){var script=document.createElement("script");script.setAttribute("src","http://www.baidu.com/olime/bdime_open.js");document.getElementsByTagName("head")[0].appendChild(script);})();'
[0] }
[0] [08:35:57.537] INFO (2295): incoming request
[0]     reqId: "req-1q"
[0]     req: {
[0]       "method": "GET",
[0]       "url": "/api/utils/updatelinks",
[0]       "hostname": "172.17.0.3:3333",
[0]       "remoteAddress": "172.17.0.1",
[0]       "remotePort": 34122
[0]     }
[0] [08:36:05.834] INFO (2295): request completed
[0]     reqId: "req-1q"
[0]     res: {
[0]       "statusCode": 200
[0]     }
[0]     responseTime: 8285.317819001153
[0] [08:36:06.471] ERROR (2295): Invalid URL
[0]     err: {
[0]       "type": "TypeError",
[0]       "message": "Invalid URL",
[0]       "stack":
[0]           TypeError: Invalid URL
[0]               at new URL (node:internal/url:775:36)
[0]               at parseIcon (file:///neonlink/server/helpers/parsers.js:34:10)
[0]               at parseHtml (file:///neonlink/server/helpers/parsers.js:21:14)
[0]               at file:///neonlink/server/logics/bookmarks.js:74:25
[0]               at Array.forEach (<anonymous>)
[0]               at batchUpdateLinks (file:///neonlink/server/logics/bookmarks.js:72:13)
[0]               at Object.<anonymous> (file:///neonlink/server/routes/api/utils/index.js:50:12)
[0]               at preHandlerCallback (/neonlink/server/node_modules/fastify/lib/handleRequest.js:137:37)
[0]               at validationCompleted (/neonlink/server/node_modules/fastify/lib/handleRequest.js:121:5)
[0]               at preValidationCallback (/neonlink/server/node_modules/fastify/lib/handleRequest.js:98:5)
[0]       "code": "ERR_INVALID_URL",
[0]       "input": "/favicon.ico",
[0]       "base": "javascript:__doPostBack('BtnNext','')"
[0]     }

`````

**Comment by AlexSciFier** [comment]
Sorry that I did not reply for a while. Apparently you have technical links in your bookmark (edge:// and javascript:, etc.). This link type is not supported in Neonlink. I will fix this problem soon.

**Comment by marklove5102** [comment]
OK
